### ISSUE TITLE
TF Keras Layers

### ISSUE THREAD

**Issue by AlessandroToschi** [DependableSystemsLab/TensorFI#4]
Is TensorFI compatible with keras layers shipped with tensorflow? 
 
My network is (just for reference) for MNIST dataset:
```
conv_1 = tf.keras.layers.Conv2D(32, (5, 5), padding="same", activation="relu")(X)
max_pool_1 = tf.keras.layers.MaxPool2D()(conv_1)
conv_2 = tf.keras.layers.Conv2D(64, (5, 5), padding="same", activation="relu")(max_pool_1)
max_pool_2 = tf.keras.layers.MaxPool2D()(conv_2)
flat = tf.keras.layers.Flatten()(max_pool_2)
dense_1 = tf.keras.layers.Dense(1024, activation="relu")(flat)
droput = tf.keras.layers.Dropout(dropout_probability)(dense_1)
dense_2 = tf.keras.layers.Dense(10, activation="softmax")(droput)
```

A typical error while trying to run the FI with demo file is:
```
E0826 17:29:57.478169 140562744907136 tensorFI.py:98] Encountered exception pyfunc_49 returns 0 values, but expects to see 1 values.
         [[node fi_dense/bias (defined at /thesis/TensorFI/TensorFI/modifyGraph.py:34) ]]

Original stack trace for u'fi_dense/bias':
```

The module has been installed as you suggest in the readme file.

**Comment by AlessandroToschi** [comment]
The "Istances" field in the configuration file is it mandatory or it can be inferred from the graph?

**Comment by AlessandroToschi** [comment]
Resolved, I figured out that I needed to specify the instances of operators.
After that, TensorFI worked!

**Comment by AlessandroToschi** [comment]
What does dynamicInstance mean?
It means that if I have a batch of 1000 elements and 10 operators it will insert 1000 * 10 faults?

**Comment by karthikp-ubc** [comment]
Thanks for the update. Does this mean that you're able to get TensorFI working with the example earlier ? We're looking into the bug and will stop doing so if this has been resolved. If so, please close the issue.

As far as dynamic instance goes, let's say you have 10 operators each of which is invoked 1000 times, it'll choose a dynamic instance among the 10*1000 operator executions (assuming all operators are included for injection), and then inject a single fault in one of those at random.

Let me know if this answers your question. If not, please create a separate issue for it. Thanks.

**Comment by karthikp-ubc** [comment]
Keras compatibility seems to work. I've added a test in the Tests directory called keras-mnist.py.
