### ISSUE TITLE
Unable to execute run on " + str(fiTensor)

### ISSUE THREAD

**Issue by xiaozhouqi** [DependableSystemsLab/TensorFI#43]
when running the LeNet.py file,  it encounts a error in tensorFI.py (101lines). It print following error information - "logging.error("Unable to execute run on " + str(fiTensor))". I don't know how this error happens, it is every appreciated for answering my question. Best wishes !

**Comment by nniranjhana** [comment]
Hi @xiaozhouqi could you attach the complete console log leading up to this error? And also what configuration file you're running the LeNet.py with?

**Comment by xiaozhouqi** [comment]
Hi @nniranjhana i run the built-in LeNet benchmark which lies in the "TensorFI-master/Tests/DNN-model/LeNet-mni
st" directory.  The configuration file is the defulat.yaml. I use debuger to keep trace of program execution. When the program step to TensorFI.py at 191 line of  code,				
                               try:
					# Call the old Run method with the fault injection Tensor
					res =  oldRun(fiTensor, feed_dict)
				except Exception as e:
					logging.error("Encountered exception " + str(e))
					logging.error("Unable to execute run on " + str(fiTensor))
					res = None	
					# continue				
				
				# Add the result to the results list
				results.append(res)
`
it encounters a exception and a None vaule is assigned to res. I think the exception is caused by the failure of running tensorflow at the new computed graph, but i don't know how to fix it. I haven't changed the code since i download it from master branche. Hope for your solutions. Best wishes!

**Comment by xiaozhouqi** [comment]
Hi @nniranjhana i run the built-in LeNet benchmark which lies in the "TensorFI-master/Tests/DNN-model/LeNet-mni
st" directory. The configuration file is the defulat.yaml. I use debuger to keep trace of program execution. When the program step to TensorFI.py at 191 line of code,
`
				try:
					# Call the old Run method with the fault injection Tensor
					import pdb
					pdb.set_trace()
					res =  oldRun(fiTensor, feed_dict)
				except Exception as e:
					logging.error("Encountered exception " + str(e))
					logging.error("Unable to execute run on " + str(fiTensor))
					res = None	
					# continue				
				
				# Add the result to the results list
				results.append(res)
`
it encounters a exception and a None vaule is assigned to res. I think the exception is caused by the failure of running tensorflow at the new computed graph, but i don't know how to fix it. I haven't changed the code since i download it from master branche. Hope for your solutions. Best wishes!

**Comment by xiaozhouqi** [comment]
Hi [@nniranjhana](https://github.com/nniranjhana) i run the built-in LeNet benchmark which lies in the "TensorFI-master/Tests/DNN-model/LeNet-mni
st" directory. The configuration file is the defulat.yaml. I use debuger to keep trace of program execution. When the program step to TensorFI.py at 191 line of code,



```
try:
\# Call the old Run method with the fault injection Tensor
	res = oldRun(fiTensor, feed_dict)
except Exception as e:
	logging.error("Encountered exception " + str(e))
	logging.error("Unable to execute run on " + str(fiTensor))
	res = None
\# continue
# Add the result to the results list
results.append(res)
```



it encounters a exception and a None vaule is assigned to res. I think the exception is caused by the failure of running tensorflow at the new computed graph, but i don't know how to fix it. I haven't changed the code since i download it from master branche. Hope for your solutions. Best wishes!

**Comment by xiaozhouqi** [comment]
Hi [@nniranjhana](https://github.com/nniranjhana) i run the built-in LeNet benchmark which lies in the "TensorFI-master/Tests/DNN-model/LeNet-mni
st" directory. The configuration file is the defulat.yaml. I use debuger to keep trace of program execution. When the program step to TensorFI.py at 191 line of code,

```
try:
# Call the old Run method with the fault injection Tensor
	res = oldRun(fiTensor, feed_dict)
except Exception as e:
	logging.error("Encountered exception " + str(e))
	logging.error("Unable to execute run on " + str(fiTensor))
	res = None
# continue
# Add the result to the results list
results.append(res)
```


it encounters a exception and a None vaule is assigned to res. I think the exception is caused by the failure of running tensorflow at the new computed graph, but i don't know how to fix it. I haven't changed the code since i download it from master branche. Hope for your solutions. Best wishes!

**Comment by xiaozhouqi** [comment]
Oh, i have solved this question. The oldRun function fails to execute due to the version of tensorflow. When undating tensorflow to the version of 1.10.0, it runs successfully. Thanks for @nniranjhana passionate helping. Best wishes!
