### ISSUE TITLE
Python version support and Windows implementation

### ISSUE THREAD

**Issue by amir-ghz** [DependableSystemsLab/TensorFI#46]
I am willing to use your tool for scientific purposes. So, have you implemented anything on windows so far to this date? 
I was also curious if anyone here has developed any model and used TensorFI within python 3.x.x?

**Comment by nniranjhana** [comment]
Hi @amir-ghz we don't have plans to support Windows and TensorFI (which currently uses TensorFlow 1) with Python 3. But we're working on supporting FI with TensorFlow 2 and Python 3.
